### ISSUE TITLE
RIOT init does not work with different RIOTBASE

### ISSUE THREAD

**Issue by martinjaeger** [attdona/riot-code#7]
If the project is not included inside the RIOT folder, but contains a link to the RIOTBASE in the Makefile, the initialization of c_cpp_properties.json and tasks.json for VS Code does not work. Error message: "Unable to setup anything: open RIOT folder first."

Two possible solutions might be: Read RIOTBASE from Makefile or define RIOTBASE in VS Code.settings.

**Comment by attdona** [comment]
The problem arises because in vscode you may have opened a `Workspace` with multiple folders and RIOT plugin have to point to the right folder before extracting the build configuration.

At the moment  it looks at a root folder named RIOT, and this cause your problem. 

An easy fix may be to skip the check of the root folder name, but in this case riot-code plugin will works only when a single project folder (`File -> Open Folder`) is opened (the "classical" vscode way).  

Should this work for you?

Greetings
Attilio

**Comment by martinjaeger** [comment]
Thanks. Tested again and works in a workspace environment.
